from . import tyre_repairer
from . import fleet_partner
from . import ipat
from . import fleet_move
from . import tire
from . import vehicle
from . import config
from . import project_task
from . import partner